### ISSUE TITLE
Villager breeding

### ISSUE THREAD

**Issue by crashoz** [GaiaMMORPG/ModPack#12]
The gamerule `/gamerule mobGriefing false` prevents villagers from picking up food. This results in them being unable to breed as they require food to be 'willing'. See https://minecraft.gamepedia.com/Villager#Willingness

**Comment by HollishKid** [comment]
Gamerule `mobGriefing` reverted to `true` and Endermans are delt with in 81bd834fec1cc52ebcb37389fa1beab7d956e28a.
