### ISSUE TITLE
Tombstone op ?

### ISSUE THREAD

**Issue by crashoz** [GaiaMMORPG/ModPack#16]
Permet entre autres de se téléporter et faire des enchantements fortune 4

**Comment by crashoz** [comment]
Après tests avec MartysFN on peut faire des enchantements potentiellement très élevés (fortune 10!). Un fix simple est de désactiver le book of disenchantement.

**Comment by HollishKid** [comment]
Tombstone a été discuté et un début de balance a été effectué dans ce commit 9e6c5627691150f5a24dc2118b19c2843d3f287c.
Il requiert plus de travail.
