### ISSUE TITLE
Mods superflus

### ISSUE THREAD

**Issue by crashoz** [GaiaMMORPG/ModPack#18]
`draw_bridge` et sa dépendance `u_team_core` peuvent etre retirés puisque `create` permet de faire des drawbriges beaucoup plus intéressants.

**Comment by crashoz** [comment]
On peut faire rotten flesh -> leather avec un ratio de 1:1 via `botania` et `nature's aura`
On peut donc supprimer `JRFTL` (just another rotten flesh to leather)

**Comment by crashoz** [comment]
Après tests, `ropebridge` ne permet que de faire des ponts horizontaux (les verticaux sont buggés dans 1.15.2). Le mod a donc peu d'utilité et peut être retiré ?

**Comment by HollishKid** [comment]
Entièrement d'accord avec tout ça.
Je supprime tout ça.
