### ISSUE TITLE
Hub & Marketplace

### ISSUE THREAD

**Issue by crashoz** [GaiaMMORPG/ModPack#22]
Créer un hub au spawn avec
- nether portal
- batiment central (spawn) 3x3 chunks
- quelques panneaux de règles
- commande /spawn

Marketplace:
- réseau de routes pour accèder aux magasins des joueurs
- chaque joueur a le droit de claim un chunk en bord de route
- magasin admin qui contient dragon egg

**Comment by HollishKid** [comment]
On peut fermer ceci @crashoz ?
