### ISSUE TITLE
Bug mod Nature Aura

### ISSUE THREAD

**Issue by KibaFox59** [GaiaMMORPG/ModPack#28]
voila il est impossible d'utilisé l'autel d'aura car il fait crash instant

**Comment by HollishKid** [comment]
Crash report donné par @Axeloow : https://pastebin.com/PubTPySD

**Comment by Eclipse2212** [comment]
@HollishKid En retirant Mixin et Performant, le mod fonctionne sans soucis (mis à jour 28.4 -> 28.5 en même temps).

**Comment by Eclipse2212** [comment]
Après tests, en supprimant performant et mixin _(sur l'environnement de prod)_ il est possible d'interagir avec l'autel de la nature sans crash.

![image](https://user-images.githubusercontent.com/5676901/95355154-82bdfa00-08c5-11eb-9478-cd45efbe6322.png)

Par ailleurs, la perte de FPS lié a la suppression de performant et MixinBootstrap impacte peu/pas les performances globales du client.

**Comment by HollishKid** [comment]
Après tests, c'était exclusivement Performant le coupable.
Il suffit d'upgrade Mixin. Lithium et Phosphor ne sont pas impliqués.
Je fermerais ce ticket avec un commit qui le fix.
