### ISSUE TITLE
Ajout d'un mod pour se tp au spawn

### ISSUE THREAD

**Issue by bahanix1371** [GaiaMMORPG/ModPack#29]
Bonjour à tous,
Je propose d'ajouter un mod qui peut permettre de se tp au spawn via le mod **Hearthstone Mod**

**- c'est un objet qui prend une place dans l'inventaire**
**- il à un cooldown après chaque utilisation (30 min)**

> lien pour voir le mod : https://www.curseforge.com/minecraft/mc-mods/hearthstone-mod

_( il est disponible en 1.15.2 mais je ne sais pas si il fonctionne sur forge 31.2.36 et je sais pas si c'est dans l'esprit du serveur, mais je trouver ça sympa ^^)_

**Comment by HollishKid** [comment]
Ce mod semble ne pas téléporter au spawn, mais au lit du joueur et ne semble donc pas faire ce qui est proposé dans le ticket.

De plus, nous avons considéré à la création du pack que c'est trop op de pouvoir se téléporter, sans coût, ni (trop) de contrainte.
Il est très peu probable que nous implémentions cette fonctionnalité, du moins sous cette forme.

**Comment by HollishKid** [comment]
Une commande `/spawn` a été ajoutée avec le commit f30153e45eb6a541a6c16ce4fe96058009394cca.
