### ISSUE TITLE
Bug mods natural's aura

### ISSUE THREAD

**Issue by WeizY31** [GaiaMMORPG/ModPack#33]
Voilà j'ai essayé une machine à aura très simple (les photos en liens)
Sauf que un problème est survenue (la machine consiste à pauser des fleurs toutes seul grâce au constructeur imperceptible puis les fleur posé son transformé en aura grâce à l'absorbeur herbivore).
Le problème est que sur le serveur les fleurs ne se posent pas pourtant on entend le bruit des fleurs posées. J'ai donc essayé en créatif et la tout fonctionne parfaitement. Je pense que le problème vient du constructeur  imperceptible..

![2020-10-20_12 32 14](https://user-images.githubusercontent.com/45913009/96574951-6a3fdd80-12d0-11eb-8725-1b37f538a293.png)

**Comment by HollishKid** [comment]
Résolu avec l'édition de cette page : https://github.com/GaiaMMORPG/ModPack/wiki/Limitations-et-Bugs-connus
